spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dokTalk?serverTimezone=Asia/Seoul
    username: root
    password: rootroot
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create # 개발 시에는 update, 운영 환경에서는 validate 또는 none 권장
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect # MySQL에 적합한 Hibernate Dialect 설정
    show-sql: true # 쿼리 로그 출력
    open-in-view: false # 성능 최적화를 위해 비활성화 권장

  # Optional: Logging 설정
  sql:
    init:
      mode: always # 스키마 및 데이터 초기화를 항상 실행 (기본값은 'embedded'임)

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG # Hibernate SQL 로그 레벨 설정
        type: TRACE # Hibernate 파라미터 포함 로그 출력
